development:
  adapter: postgresql
  encoding: unicode
  host: db
  database: url_shortener_db_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: db
  database: url_shortener_db_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: db
  database: url_shortener_db_production
  pool: 5
  username: postgres
  password: